# Generated by Django 2.2 on 2019-05-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_menu_is_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_sub',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
        migrations.AlterField(
            model_name='menu',
            name='submenus',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_menus', to='sign.Submenu'),
        ),
    ]
