# Generated by Django 2.2 on 2019-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20190519_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='submenus',
            field=models.ManyToManyField(blank=True, null=True, to='sign.Submenu'),
        ),
    ]
